services:
  backend:
    build:
      context: .
      dockerfile: ui/backend/Dockerfile
    container_name: sagemaker-research-platform-backend
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION:-eu-central-1}
      AWS_REGION: ${AWS_DEFAULT_REGION:-eu-central-1}
      PROJECT_ROOT: /workspace
    volumes:
      - ./:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "7474:8000"

  frontend:
    build:
      context: ./ui/frontend
      dockerfile: Dockerfile
    container_name: sagemaker-research-platform-frontend
    depends_on:
      - backend
    ports:
      - "7475:80"
